config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    www:
      branch: main
      repo: https://www.github.com/haddocking/haddock3
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      www git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-smalt-baboon.sh
        container: qc.acc_randy-pink-hare
  QC.Doc:
    repos:
      www find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-magnolia-pig.sh
        container: qc.doc_pokey-brown-sheepdog
      www git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cinnamon-toad.sh
        container: qc.doc_baggy-eggplant-ferret
      www markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-malachite-whippet.sh
        container: qc.doc_boozy-magenta-sheepdog
      www restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-linen-kiwi.sh
        container: qc.doc_smelly-copper-woodpecker
  QC.Lic:
    repos:
      www licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-auburn-sparrow.sh
        container: qc.lic_wheezy-ruby-abyssinian
  QC.Sec:
    repos:
      www bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ivory-albatross.sh
        container: qc.sec_gimpy-purple-blue
  QC.Sty:
    repos:
      www flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-harlequin-mule.sh
        container: qc.sty_scummy-pink-gar
      www jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-orchid-worm.sh
        container: qc.sty_ugly-russet-chinook
  QC.Ver:
    repos:
      www get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-persimmon-vulture.sh
        container: qc.ver_lovely-razzmatazz-barb
timeout: 5400
